# Generated by Django 3.1.4 on 2021-04-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enrool',
        ),
    ]
