# Generated by Django 3.1.4 on 2021-04-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enroll', '0002_delete_enrool'),
    ]

    operations = [
        migrations.CreateModel(
            name='newModel',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
            ],
        ),
    ]
